import { CountryModel } from 'src/app/shared/models/country.model';

export var ProvidedCountryNames: CountryModel [] = [
    { Name: "Afghanistan" },
    { Name: "Albania" },
    { Name: "Algeria" },
    { Name: "American Samoa" },
    { Name: "Andorra" },
    { Name: "Angola" },
    { Name: "Anguilla" },
    { Name: "Antarctica" },
    { Name: "Antigua and Barbuda" },
    { Name: "Argentina" },
    { Name: "Armenia" },
    { Name: "Aruba" },
    { Name: "Australia" },
    { Name: "Austria" },
    { Name: "Azerbaijan" },
    { Name: "Bahamas" },
    { Name: "Bahrain" },
    { Name: "Bangladesh" },
    { Name: "Barbados" },
    { Name: "Belarus" },
    { Name: "Belgium" },
    { Name: "Belize" },
    { Name: "Benin" },
    { Name: "Bermuda" },
    { Name: "Bhutan" },
    { Name: "Bolivia (Plurinational State of)" },
    { Name: "Bonaire, Sint Eustatius and Saba" },
    { Name: "Bosnia and Herzegovina" },
    { Name: "Botswana" },
    { Name: "Bouvet Island" },
    { Name: "Brazil" },
    { Name: "British Indian Ocean Territory (the)" },
    { Name: "Brunei Darussalam" },
    { Name: "Bulgaria" },
    { Name: "Burkina Faso" },
    { Name: "Burundi" },
    { Name: "Cabo Verde" },
    { Name: "Cambodia" },
    { Name: "Cameroon" },
    { Name: "Canada" },
    { Name: "Cayman Islands (the)" },
    { Name: "Central African Republic (the)" },
    { Name: "Chad" },
    { Name: "Chile" },
    { Name: "China" },
    { Name: "Christmas Island" },
    { Name: "Cocos (Keeling) Islands (the)" },
    { Name: "Colombia" },
    { Name: "Comoros" },
    { Name: "Congo (Democratic Republic)" },
    { Name: "Congo" },
    { Name: "Cook Islands" },
    { Name: "Costa Rica" },
    { Name: "Croatia" },
    { Name: "Cuba" },
    { Name: "Curaçao" },
    { Name: "Cyprus"},
    { Name: "Czechia"},
    { Name: "Côte d'Ivoire"},
    { Name: "Denmark"},
    { Name: "Djibouti"},
    { Name: "Dominica"},
    { Name: "Dominican Republic (the)"},
    { Name: "Ecuador"},
    { Name: "Egypt"},
    { Name: "El Salvador"},
    { Name: "Equatorial Guinea"},
    { Name: "Eritrea"},
    { Name: "Estonia"},
    { Name: "Eswatini"},
    { Name: "Ethiopia"},
    { Name: "Falkland Islands (the) [Malvinas]"},
    { Name: "Faroe Islands (the)"},
    { Name: "Fiji"},
    { Name: "Finland"},
    { Name: "France"},
    { Name: "French Guiana"},
    { Name: "French Polynesia"},
    { Name: "French Southern Territories (the)"},
    { Name: "Gabon"},
    { Name: "Gambia (the)"},
    { Name: "Georgia"},
    { Name: "Germany"},
    { Name: "Ghana"},
    { Name: "Gibraltar"},
    { Name: "Greece"},
    { Name: "Greenland"},
    { Name: "Grenada" },
    { Name: "Guadeloupe" },
    { Name: "Guam" },
    { Name: "Guatemala" },
    { Name: "Guernsey" },
    { Name: "Guinea" },
    { Name: "Guinea-Bissau" },
    { Name: "Guyana" },
    { Name: "Haiti" },
    { Name: "Heard Island and McDonald Islands" },
    { Name: "Holy See (the)" },
    { Name: "Honduras" },
    { Name: "Hong Kong" },
    { Name: "Hungary" },
    { Name: "Iceland" },
    { Name: "India" },
    { Name: "Indonesia" },
    { Name: "Iran (Islamic Republic of)"},
    { Name: "Iraq" },
    { Name: "Ireland" },
    { Name: "Isle of Man" },
    { Name: "Israel" },
    { Name: "Italy" },
    { Name: "Jamaica" },
    { Name: "Japan" },
    { Name: "Jersey" },
    { Name: "Jordan" },
    { Name: "Kazakhstan" },
    { Name: "Kenya" },
    { Name: "Kiribati"},
    { Name: "Korea (the Democratic People's Republic of)"},
    { Name: "Korea (the Republic of)"},
    { Name: "Kuwait"},
    { Name: "Kyrgyzstan"},
    { Name: "Lao People's Democratic Republic (the)"},
    { Name: "Latvia"},
    { Name: "Lebanon"},
    { Name: "Lesotho"},
    { Name: "Liberia"},
    { Name: "Libya"},
    { Name: "Liechtenstein"},
    { Name: "Lithuania"},
    { Name: "Luxembourg"},
    { Name: "Macao"},
    { Name: "Madagascar"},
    { Name: "Malawi"},
    { Name: "Malaysia"},
    { Name: "Maldives"},
    { Name: "Mali"},
    { Name: "Malta"},
    { Name: "Marshall Islands (the)"},
    { Name: "Martinique"},
    { Name: "Mauritania"},
    { Name: "Mauritius"},
    { Name: "Mayotte"},
    { Name: "Mexico"},
    { Name: "Micronesia (Federated States of)"},
    { Name: "Moldova (the Republic of)"},
    { Name: "Monaco"},
    { Name: "Mongolia"},
    { Name: "Montenegro"},
    { Name: "Montserrat"},
    { Name: "Morocco" },
    { Name: "Mozambique" },
    { Name: "Myanmar" },
    { Name: "Namibia" },
    { Name: "Nauru" },
    { Name: "Nepal" },
    { Name: "Netherlands (the)" },
    { Name: "New Caledonia" },
    { Name: "New Zealand" },
    { Name: "Nicaragua" },
    { Name: "Niger (the)" },
    { Name: "Nigeria" },
    { Name: "Niue" },
    { Name: "Norfolk Island" },
    { Name: "Northern Mariana Islands (the)" },
    { Name: "Norway" },
    { Name: "Oman" },
    { Name: "Pakistan" },
    { Name: "Palau" },
    { Name: "Palestine, State of" },
    { Name: "Panama" },
    { Name: "Papua New Guinea" },
    { Name: "Paraguay" },
    { Name: "Peru" },
    { Name: "Philippines (the)" },
    { Name: "Pitcairn" },
    { Name: "Poland" },
    { Name: "Portugal" },
    { Name: "Puerto Rico" },
    { Name: "Qatar" },
    { Name: "Republic of North Macedonia" },
    { Name: "Romania"},
    { Name: "Russian Federation (the)"},
    { Name: "Rwanda"},
    { Name: "Réunion"},
    { Name: "Saint Barthélemy"},
    { Name: "Saint Helena, Ascension and Tristan da Cunha"},
    { Name: "Saint Kitts and Nevis"},
    { Name: "Saint Lucia"},
    { Name: "Saint Martin (French part)"},
    { Name: "Saint Pierre and Miquelon"},
    { Name: "Saint Vincent and the Grenadines"},
    { Name: "Samoa"},
    { Name: "San Marino"},
    { Name: "Sao Tome and Principe"},
    { Name: "Saudi Arabia"},
    { Name: "Senegal"},
    { Name: "Serbia"},
    { Name: "Seychelles"},
    { Name: "Sierra Leone"},
    { Name: "Singapore"},
    { Name: "Sint Maarten (Dutch part)"},
    { Name: "Slovakia"},
    { Name: "Slovenia"},
    { Name: "Solomon Islands"},
    { Name: "Somalia"},
    { Name: "South Africa"},
    { Name: "South Georgia and the South Sandwich Islands"},
    { Name: "South Sudan"},
    { Name: "Spain"},
    { Name: "Sri Lanka"},
    { Name: "Sudan (the)"},
    { Name: "Suriname"},
    { Name: "Svalbard and Jan Mayen"},
    { Name: "Sweden"},
    { Name: "Switzerland"},
    { Name: "Syrian Arab Republic"},
    { Name: "Taiwan"},
    { Name: "Tajikistan"},
    { Name: "Tanzania, United Republic of"},
    { Name: "Thailand"},
    { Name: "Timor-Leste"},
    { Name: "Togo"},
    { Name: "Tokelau"},
    { Name: "Tonga"},
    { Name: "Trinidad and Tobago"},
    { Name: "Tunisia"},
    { Name: "Turkey"},
    { Name: "Turkmenistan"},
    { Name: "Turks and Caicos Islands (the)"},
    { Name: "Tuvalu"},
    { Name: "Uganda"},
    { Name: "Ukraine"},
    { Name: "United Arab Emirates (the)"},
    { Name: "United Kingdom of Great Britain and Northern Ireland (the)"},
    { Name: "United States Minor Outlying Islands (the)"},
    { Name: "United States of America (the)"},
    { Name: "Uruguay"},
    { Name: "Uzbekistan"},
    { Name: "Vanuatu"},
    { Name: "Venezuela (Bolivarian Republic of)"},
    { Name: "Viet Nam"},
    { Name: "Virgin Islands (British)"},
    { Name: "Virgin Islands (U.S.)"},
    { Name: "Wallis and Futuna"},
    { Name: "Western Sahara"},
    { Name: "Yemen"},
    { Name: "Zambia"},
    { Name: "Zimbabwe"},
    { Name: "Åland Islands" }
];